language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.8.17
  - DJANGO=1.9.12
  - DJANGO=1.10.5

install:
  - pip install Django==$DJANGO times da-vinci pillow redis shortuuid
  - sudo apt-get install -qq optipng

script: make test
services: redis
